//go:build go1.22

// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for StatusSchema.
const (
	Active      StatusSchema = "active"
	Failed      StatusSchema = "failed"
	Pending     StatusSchema = "pending"
	Terminating StatusSchema = "terminating"
)

// CreateProbeRequest defines model for CreateProbeRequest.
type CreateProbeRequest struct {
	// Labels A set of key-value pairs that can be used to organize and select probes.
	Labels *LabelsSchema `json:"labels,omitempty"`

	// StaticUrl The static URL to be probed.
	StaticUrl StaticUrlSchema `json:"static_url"`
}

// ErrorObject defines model for ErrorObject.
type ErrorObject struct {
	// Message A human-readable error message.
	Message string `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ErrorObject `json:"error"`
}

// LabelsSchema A set of key-value pairs that can be used to organize and select probes.
type LabelsSchema map[string]string

// ProbeIdSchema The unique identifier of a probe (UUID format).
type ProbeIdSchema = openapi_types.UUID

// ProbeObject Represents a single probe configuration.
type ProbeObject struct {
	// Id The unique identifier of a probe (UUID format).
	Id ProbeIdSchema `json:"id"`

	// Labels A set of key-value pairs that can be used to organize and select probes.
	Labels *LabelsSchema `json:"labels,omitempty"`

	// StaticUrl The static URL to be probed.
	StaticUrl StaticUrlSchema `json:"static_url"`

	// Status The current status of the probe.
	Status StatusSchema `json:"status"`
}

// ProbesArrayResponse defines model for ProbesArrayResponse.
type ProbesArrayResponse struct {
	// Probes Array containing one or more probe objects.
	Probes []ProbeObject `json:"probes"`
}

// StaticUrlSchema The static URL to be probed.
type StaticUrlSchema = string

// StatusSchema The current status of the probe.
type StatusSchema string

// UpdateProbeRequest Fields to update for a probe.
type UpdateProbeRequest struct {
	// Status The current status of the probe.
	Status *StatusSchema `json:"status,omitempty"`
}

// WarningObject defines model for WarningObject.
type WarningObject struct {
	// Message A human-readable error message indicating the resource was not found.
	Message string `json:"message"`
}

// WarningResponse defines model for WarningResponse.
type WarningResponse struct {
	Warning WarningObject `json:"warning"`
}

// LabelSelectorQueryParam defines model for LabelSelectorQueryParam.
type LabelSelectorQueryParam = string

// ProbeIdPathParam The unique identifier of a probe (UUID format).
type ProbeIdPathParam = ProbeIdSchema

// ListProbesParams defines parameters for ListProbes.
type ListProbesParams struct {
	// LabelSelector A comma-separated list of key=value labels to filter on.
	LabelSelector *LabelSelectorQueryParam `form:"label_selector,omitempty" json:"label_selector,omitempty"`
}

// CreateProbeJSONRequestBody defines body for CreateProbe for application/json ContentType.
type CreateProbeJSONRequestBody = CreateProbeRequest

// UpdateProbeJSONRequestBody defines body for UpdateProbe for application/json ContentType.
type UpdateProbeJSONRequestBody = UpdateProbeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get a list of all configured probes
	// (GET /probes)
	ListProbes(w http.ResponseWriter, r *http.Request, params ListProbesParams)
	// Creates a new probe
	// (POST /probes)
	CreateProbe(w http.ResponseWriter, r *http.Request)
	// Deletes a probe matching provided ID
	// (DELETE /probes/{probe_id})
	DeleteProbe(w http.ResponseWriter, r *http.Request, probeId ProbeIdPathParam)
	// Get a probe by its ID
	// (GET /probes/{probe_id})
	GetProbeById(w http.ResponseWriter, r *http.Request, probeId ProbeIdPathParam)
	// Updates a probe by its ID
	// (PATCH /probes/{probe_id})
	UpdateProbe(w http.ResponseWriter, r *http.Request, probeId ProbeIdPathParam)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListProbes operation middleware
func (siw *ServerInterfaceWrapper) ListProbes(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProbesParams

	// ------------- Optional query parameter "label_selector" -------------

	err = runtime.BindQueryParameter("form", true, false, "label_selector", r.URL.Query(), &params.LabelSelector)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "label_selector", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProbes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProbe operation middleware
func (siw *ServerInterfaceWrapper) CreateProbe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProbe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteProbe operation middleware
func (siw *ServerInterfaceWrapper) DeleteProbe(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "probe_id" -------------
	var probeId ProbeIdPathParam

	err = runtime.BindStyledParameterWithOptions("simple", "probe_id", r.PathValue("probe_id"), &probeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "probe_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProbe(w, r, probeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProbeById operation middleware
func (siw *ServerInterfaceWrapper) GetProbeById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "probe_id" -------------
	var probeId ProbeIdPathParam

	err = runtime.BindStyledParameterWithOptions("simple", "probe_id", r.PathValue("probe_id"), &probeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "probe_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProbeById(w, r, probeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProbe operation middleware
func (siw *ServerInterfaceWrapper) UpdateProbe(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "probe_id" -------------
	var probeId ProbeIdPathParam

	err = runtime.BindStyledParameterWithOptions("simple", "probe_id", r.PathValue("probe_id"), &probeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "probe_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProbe(w, r, probeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/probes", wrapper.ListProbes)
	m.HandleFunc("POST "+options.BaseURL+"/probes", wrapper.CreateProbe)
	m.HandleFunc("DELETE "+options.BaseURL+"/probes/{probe_id}", wrapper.DeleteProbe)
	m.HandleFunc("GET "+options.BaseURL+"/probes/{probe_id}", wrapper.GetProbeById)
	m.HandleFunc("PATCH "+options.BaseURL+"/probes/{probe_id}", wrapper.UpdateProbe)

	return m
}

type ListProbesRequestObject struct {
	Params ListProbesParams
}

type ListProbesResponseObject interface {
	VisitListProbesResponse(w http.ResponseWriter) error
}

type ListProbes200JSONResponse ProbesArrayResponse

func (response ListProbes200JSONResponse) VisitListProbesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListProbes400JSONResponse ErrorResponse

func (response ListProbes400JSONResponse) VisitListProbesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateProbeRequestObject struct {
	Body *CreateProbeJSONRequestBody
}

type CreateProbeResponseObject interface {
	VisitCreateProbeResponse(w http.ResponseWriter) error
}

type CreateProbe201JSONResponse ProbeObject

func (response CreateProbe201JSONResponse) VisitCreateProbeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateProbe409JSONResponse ErrorResponse

func (response CreateProbe409JSONResponse) VisitCreateProbeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateProbe500JSONResponse ErrorResponse

func (response CreateProbe500JSONResponse) VisitCreateProbeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteProbeRequestObject struct {
	ProbeId ProbeIdPathParam `json:"probe_id"`
}

type DeleteProbeResponseObject interface {
	VisitDeleteProbeResponse(w http.ResponseWriter) error
}

type DeleteProbe204Response struct {
}

func (response DeleteProbe204Response) VisitDeleteProbeResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteProbe404JSONResponse WarningResponse

func (response DeleteProbe404JSONResponse) VisitDeleteProbeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetProbeByIdRequestObject struct {
	ProbeId ProbeIdPathParam `json:"probe_id"`
}

type GetProbeByIdResponseObject interface {
	VisitGetProbeByIdResponse(w http.ResponseWriter) error
}

type GetProbeById200JSONResponse ProbeObject

func (response GetProbeById200JSONResponse) VisitGetProbeByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProbeById404JSONResponse WarningResponse

func (response GetProbeById404JSONResponse) VisitGetProbeByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProbeRequestObject struct {
	ProbeId ProbeIdPathParam `json:"probe_id"`
	Body    *UpdateProbeJSONRequestBody
}

type UpdateProbeResponseObject interface {
	VisitUpdateProbeResponse(w http.ResponseWriter) error
}

type UpdateProbe200JSONResponse ProbeObject

func (response UpdateProbe200JSONResponse) VisitUpdateProbeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProbe400JSONResponse ErrorResponse

func (response UpdateProbe400JSONResponse) VisitUpdateProbeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProbe404JSONResponse WarningResponse

func (response UpdateProbe404JSONResponse) VisitUpdateProbeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get a list of all configured probes
	// (GET /probes)
	ListProbes(ctx context.Context, request ListProbesRequestObject) (ListProbesResponseObject, error)
	// Creates a new probe
	// (POST /probes)
	CreateProbe(ctx context.Context, request CreateProbeRequestObject) (CreateProbeResponseObject, error)
	// Deletes a probe matching provided ID
	// (DELETE /probes/{probe_id})
	DeleteProbe(ctx context.Context, request DeleteProbeRequestObject) (DeleteProbeResponseObject, error)
	// Get a probe by its ID
	// (GET /probes/{probe_id})
	GetProbeById(ctx context.Context, request GetProbeByIdRequestObject) (GetProbeByIdResponseObject, error)
	// Updates a probe by its ID
	// (PATCH /probes/{probe_id})
	UpdateProbe(ctx context.Context, request UpdateProbeRequestObject) (UpdateProbeResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListProbes operation middleware
func (sh *strictHandler) ListProbes(w http.ResponseWriter, r *http.Request, params ListProbesParams) {
	var request ListProbesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListProbes(ctx, request.(ListProbesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProbes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListProbesResponseObject); ok {
		if err := validResponse.VisitListProbesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateProbe operation middleware
func (sh *strictHandler) CreateProbe(w http.ResponseWriter, r *http.Request) {
	var request CreateProbeRequestObject

	var body CreateProbeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProbe(ctx, request.(CreateProbeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProbe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateProbeResponseObject); ok {
		if err := validResponse.VisitCreateProbeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteProbe operation middleware
func (sh *strictHandler) DeleteProbe(w http.ResponseWriter, r *http.Request, probeId ProbeIdPathParam) {
	var request DeleteProbeRequestObject

	request.ProbeId = probeId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteProbe(ctx, request.(DeleteProbeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteProbe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteProbeResponseObject); ok {
		if err := validResponse.VisitDeleteProbeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProbeById operation middleware
func (sh *strictHandler) GetProbeById(w http.ResponseWriter, r *http.Request, probeId ProbeIdPathParam) {
	var request GetProbeByIdRequestObject

	request.ProbeId = probeId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProbeById(ctx, request.(GetProbeByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProbeById")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProbeByIdResponseObject); ok {
		if err := validResponse.VisitGetProbeByIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateProbe operation middleware
func (sh *strictHandler) UpdateProbe(w http.ResponseWriter, r *http.Request, probeId ProbeIdPathParam) {
	var request UpdateProbeRequestObject

	request.ProbeId = probeId

	var body UpdateProbeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateProbe(ctx, request.(UpdateProbeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateProbe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateProbeResponseObject); ok {
		if err := validResponse.VisitUpdateProbeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xYXW/buBL9KwTvBXovIH/1pl8G+pA0d7sGik022WAfiiCgxZHNViIVcuTEG+i/L4aU",
	"bMmSN2nXG9QPAWxR5JkzZ84M88Bjk+VGg0bHpw88F1ZkgGD9t09iDuklpBCjsb8WYNfn9JweSXCxVTkq",
	"o/mUH7PYZJkYOKANECRLlUNmEvYV1u9XIi2ApbSZY2hYolIEy4we8ojDvcjyFPiUx2nhEOyNku/ly3fj",
	"ZAIweB2/OhoczceTwbsxvB7IN+PJm6O3yfjtq0mUW7USCO/RFsAjrgjILYHkEdcioy39mTeuioBH3MVL",
	"yAQFgOucVji0Si94WUb83Jo5zOS5wOWeMH9bApudUli4BJbTeorHAloFK2iH85QYati5wOUWtd/4Rkke",
	"cQu3hbIg+ZSibOL/t4WET/m/RtsEjsJTN6oiuQyLSwquekRvfrAgEPyaC7gtwKHPvDU5WFTg14RkPXaO",
	"14erj4m4Q4Eqvils+tibl37llU03GJuxfm7udB3VuTLzLxAjHfR/a409C1872DNwTiygT6XLIhN6YEFI",
	"MU+BAW3DqvXt7M30SqRKBtWyWkEsMTYTyKMe+TTh1xD2Yr8AlxvtoIveY3qMvmb8u2eHDfpObqVr+sCF",
	"lIqoEel5C8JObFGHRgd1bQ9CbedCWcdwKZDFQrM5sMKBpNowdiG0+gOY0LKiMRSOa/H90Kj+p9dO5QB8",
	"yr0HlD0xt0uht6ILrW4LYEqCRpUocqaEiaq8/3N1NTut0v7f7yrwSjJTXhS+pDvseohbMbcBXkBuwVHy",
	"mWBO6UVaG09sdKIWhRW0cujZaCaRePwml4iev+jDy4V7youF22MVntQGiM2m1/vk4I6tFev9JRj02eMf",
	"9BrxjkJppRfMaGBkIMbWSQkneW0rhMw9KQdnG3gVXkEHdQKtYPWFtctsr84DR+zq4hMV5ryCLNuiXiLm",
	"bjoaiVwNq18HVWkOE2OGElZuqRIcGrtoidsz39F2K3O9qOLCWtDIQtJavdUj00Xmgwctac+IixjVihp+",
	"IlQKvqLAZkoLpOfXzWA2Szu4rnLZ0wPb6H5SkEo/sBR+NblA7QvdevtOJXdS+buwpK0DNzemtFSxp8jz",
	"a8GZwsbA7oRj2iBLTKF3pODZYXcKlzT0vLivPoOeP/XnxXavv9UjKxL2l+hdWPAY3W0ydxHUm3QR0Eql",
	"E9ND8/nM6yATWiyIzZNUxF/n5p4Fa6GwFXr+Ln4+O7lkl2uNS0AVu2oFOz6f8YivwLqw5Xg4Hk4oapOD",
	"FrniU/6/4WToG5zApY93tPWkBXhZEBve+mfUMD8phxsAzSH+cz9B2yWjfUN+eU1shQT4g1+Ox75RG42g",
	"PQaR56lXldGjL46CefiWCXXHhz3ru6Ku7xEiTTcdD+RmhCgjfnRAWO3ZrAdQPRbaYBpsy+PQy8sVWSbs",
	"mk/5R0Am/ho+aUUsXNPby4jnxvUkuDG0V9cCcHhi5PpgsfdcC8p2xdCQVXZEMTmsKM4aJdjmPvhR7GFK",
	"5oo4BueSIk3XlQ7ePZ8Ojqt+792RDNWJrO6wNIUwkZIRrxncK4dBqK+eV6gIVgu6utgV2NANdjUaUk6T",
	"pYa7EFGfJsuo9p/RQ303LYM1poDQFeup/70W67fZUecW3uNDR11fDuIIgHbEwX4xrCK9EsrRwfKw26j2",
	"yrbRY9s5CFy5zYUjExgvqbHk1qyUBMlmp/1G0dsIPkLoAyfrmfxHuB8/V7l/2LHLLTPVgFiz8wMmNZh/",
	"gD1fM4VubxZziqqbx8aAeqg0Hr5l9EzRT2oZ4+dtGWF8720ZP8ro8KMJOGTWPU3E/h4Tfty15bNa1I5Z",
	"SH0W0LAM0NJAvBmDmv/4dLy8Lv8MAAD//5xUgo+YFgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
