//go:build go1.22

// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for StatusSchema.
const (
	Active      StatusSchema = "active"
	Failed      StatusSchema = "failed"
	Pending     StatusSchema = "pending"
	Terminating StatusSchema = "terminating"
)

// CreateProbeRequest defines model for CreateProbeRequest.
type CreateProbeRequest struct {
	// Labels A set of key-value pairs that can be used to organize and select probes.
	Labels *LabelsSchema `json:"labels,omitempty"`

	// StaticUrl The static URL to be probed.
	StaticUrl StaticUrlSchema `json:"static_url"`
}

// ErrorObject defines model for ErrorObject.
type ErrorObject struct {
	// Message A human-readable error message.
	Message string `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ErrorObject `json:"error"`
}

// LabelsSchema A set of key-value pairs that can be used to organize and select probes.
type LabelsSchema map[string]string

// ProbeIdSchema The unique identifier of a probe (UUID format).
type ProbeIdSchema = openapi_types.UUID

// ProbeObject Represents a single probe configuration.
type ProbeObject struct {
	// Id The unique identifier of a probe (UUID format).
	Id ProbeIdSchema `json:"id"`

	// Labels A set of key-value pairs that can be used to organize and select probes.
	Labels *LabelsSchema `json:"labels,omitempty"`

	// StaticUrl The static URL to be probed.
	StaticUrl StaticUrlSchema `json:"static_url"`

	// Status The current status of the probe.
	Status StatusSchema `json:"status"`
}

// ProbesArrayResponse defines model for ProbesArrayResponse.
type ProbesArrayResponse struct {
	// Probes Array containing one or more probe objects.
	Probes []ProbeObject `json:"probes"`
}

// StaticUrlSchema The static URL to be probed.
type StaticUrlSchema = string

// StatusSchema The current status of the probe.
type StatusSchema string

// UpdateProbeRequest Fields to update for a probe.
type UpdateProbeRequest struct {
	// Status The current status of the probe.
	Status *StatusSchema `json:"status,omitempty"`
}

// WarningObject defines model for WarningObject.
type WarningObject struct {
	// Message A human-readable error message indicating the resource was not found.
	Message string `json:"message"`
}

// WarningResponse defines model for WarningResponse.
type WarningResponse struct {
	Warning WarningObject `json:"warning"`
}

// LabelSelectorQueryParam defines model for LabelSelectorQueryParam.
type LabelSelectorQueryParam = string

// ProbeIdPathParam The unique identifier of a probe (UUID format).
type ProbeIdPathParam = ProbeIdSchema

// ListProbesParams defines parameters for ListProbes.
type ListProbesParams struct {
	// LabelSelector A comma-separated list of key=value labels to filter on.
	LabelSelector *LabelSelectorQueryParam `form:"label_selector,omitempty" json:"label_selector,omitempty"`
}

// CreateProbeJSONRequestBody defines body for CreateProbe for application/json ContentType.
type CreateProbeJSONRequestBody = CreateProbeRequest

// UpdateProbeJSONRequestBody defines body for UpdateProbe for application/json ContentType.
type UpdateProbeJSONRequestBody = UpdateProbeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get a list of all configured probes
	// (GET /metrics/probes)
	ListProbes(w http.ResponseWriter, r *http.Request, params ListProbesParams)
	// Creates a new probe
	// (POST /metrics/probes)
	CreateProbe(w http.ResponseWriter, r *http.Request)
	// Deletes a probe matching provided ID
	// (DELETE /metrics/probes/{probe_id})
	DeleteProbe(w http.ResponseWriter, r *http.Request, probeId ProbeIdPathParam)
	// Get a probe by its ID
	// (GET /metrics/probes/{probe_id})
	GetProbeById(w http.ResponseWriter, r *http.Request, probeId ProbeIdPathParam)
	// Updates a probe by its ID
	// (PATCH /metrics/probes/{probe_id})
	UpdateProbe(w http.ResponseWriter, r *http.Request, probeId ProbeIdPathParam)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListProbes operation middleware
func (siw *ServerInterfaceWrapper) ListProbes(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProbesParams

	// ------------- Optional query parameter "label_selector" -------------

	err = runtime.BindQueryParameter("form", true, false, "label_selector", r.URL.Query(), &params.LabelSelector)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "label_selector", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProbes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProbe operation middleware
func (siw *ServerInterfaceWrapper) CreateProbe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProbe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteProbe operation middleware
func (siw *ServerInterfaceWrapper) DeleteProbe(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "probe_id" -------------
	var probeId ProbeIdPathParam

	err = runtime.BindStyledParameterWithOptions("simple", "probe_id", r.PathValue("probe_id"), &probeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "probe_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProbe(w, r, probeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProbeById operation middleware
func (siw *ServerInterfaceWrapper) GetProbeById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "probe_id" -------------
	var probeId ProbeIdPathParam

	err = runtime.BindStyledParameterWithOptions("simple", "probe_id", r.PathValue("probe_id"), &probeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "probe_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProbeById(w, r, probeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProbe operation middleware
func (siw *ServerInterfaceWrapper) UpdateProbe(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "probe_id" -------------
	var probeId ProbeIdPathParam

	err = runtime.BindStyledParameterWithOptions("simple", "probe_id", r.PathValue("probe_id"), &probeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "probe_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProbe(w, r, probeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/metrics/probes", wrapper.ListProbes)
	m.HandleFunc("POST "+options.BaseURL+"/metrics/probes", wrapper.CreateProbe)
	m.HandleFunc("DELETE "+options.BaseURL+"/metrics/probes/{probe_id}", wrapper.DeleteProbe)
	m.HandleFunc("GET "+options.BaseURL+"/metrics/probes/{probe_id}", wrapper.GetProbeById)
	m.HandleFunc("PATCH "+options.BaseURL+"/metrics/probes/{probe_id}", wrapper.UpdateProbe)

	return m
}

type ListProbesRequestObject struct {
	Params ListProbesParams
}

type ListProbesResponseObject interface {
	VisitListProbesResponse(w http.ResponseWriter) error
}

type ListProbes200JSONResponse ProbesArrayResponse

func (response ListProbes200JSONResponse) VisitListProbesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListProbes400JSONResponse ErrorResponse

func (response ListProbes400JSONResponse) VisitListProbesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateProbeRequestObject struct {
	Body *CreateProbeJSONRequestBody
}

type CreateProbeResponseObject interface {
	VisitCreateProbeResponse(w http.ResponseWriter) error
}

type CreateProbe201JSONResponse ProbeObject

func (response CreateProbe201JSONResponse) VisitCreateProbeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateProbe409JSONResponse ErrorResponse

func (response CreateProbe409JSONResponse) VisitCreateProbeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateProbe500JSONResponse ErrorResponse

func (response CreateProbe500JSONResponse) VisitCreateProbeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteProbeRequestObject struct {
	ProbeId ProbeIdPathParam `json:"probe_id"`
}

type DeleteProbeResponseObject interface {
	VisitDeleteProbeResponse(w http.ResponseWriter) error
}

type DeleteProbe204Response struct {
}

func (response DeleteProbe204Response) VisitDeleteProbeResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteProbe404JSONResponse WarningResponse

func (response DeleteProbe404JSONResponse) VisitDeleteProbeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetProbeByIdRequestObject struct {
	ProbeId ProbeIdPathParam `json:"probe_id"`
}

type GetProbeByIdResponseObject interface {
	VisitGetProbeByIdResponse(w http.ResponseWriter) error
}

type GetProbeById200JSONResponse ProbeObject

func (response GetProbeById200JSONResponse) VisitGetProbeByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProbeById404JSONResponse WarningResponse

func (response GetProbeById404JSONResponse) VisitGetProbeByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProbeRequestObject struct {
	ProbeId ProbeIdPathParam `json:"probe_id"`
	Body    *UpdateProbeJSONRequestBody
}

type UpdateProbeResponseObject interface {
	VisitUpdateProbeResponse(w http.ResponseWriter) error
}

type UpdateProbe200JSONResponse ProbeObject

func (response UpdateProbe200JSONResponse) VisitUpdateProbeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProbe400JSONResponse ErrorResponse

func (response UpdateProbe400JSONResponse) VisitUpdateProbeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProbe404JSONResponse WarningResponse

func (response UpdateProbe404JSONResponse) VisitUpdateProbeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get a list of all configured probes
	// (GET /metrics/probes)
	ListProbes(ctx context.Context, request ListProbesRequestObject) (ListProbesResponseObject, error)
	// Creates a new probe
	// (POST /metrics/probes)
	CreateProbe(ctx context.Context, request CreateProbeRequestObject) (CreateProbeResponseObject, error)
	// Deletes a probe matching provided ID
	// (DELETE /metrics/probes/{probe_id})
	DeleteProbe(ctx context.Context, request DeleteProbeRequestObject) (DeleteProbeResponseObject, error)
	// Get a probe by its ID
	// (GET /metrics/probes/{probe_id})
	GetProbeById(ctx context.Context, request GetProbeByIdRequestObject) (GetProbeByIdResponseObject, error)
	// Updates a probe by its ID
	// (PATCH /metrics/probes/{probe_id})
	UpdateProbe(ctx context.Context, request UpdateProbeRequestObject) (UpdateProbeResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListProbes operation middleware
func (sh *strictHandler) ListProbes(w http.ResponseWriter, r *http.Request, params ListProbesParams) {
	var request ListProbesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListProbes(ctx, request.(ListProbesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProbes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListProbesResponseObject); ok {
		if err := validResponse.VisitListProbesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateProbe operation middleware
func (sh *strictHandler) CreateProbe(w http.ResponseWriter, r *http.Request) {
	var request CreateProbeRequestObject

	var body CreateProbeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProbe(ctx, request.(CreateProbeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProbe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateProbeResponseObject); ok {
		if err := validResponse.VisitCreateProbeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteProbe operation middleware
func (sh *strictHandler) DeleteProbe(w http.ResponseWriter, r *http.Request, probeId ProbeIdPathParam) {
	var request DeleteProbeRequestObject

	request.ProbeId = probeId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteProbe(ctx, request.(DeleteProbeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteProbe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteProbeResponseObject); ok {
		if err := validResponse.VisitDeleteProbeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProbeById operation middleware
func (sh *strictHandler) GetProbeById(w http.ResponseWriter, r *http.Request, probeId ProbeIdPathParam) {
	var request GetProbeByIdRequestObject

	request.ProbeId = probeId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProbeById(ctx, request.(GetProbeByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProbeById")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProbeByIdResponseObject); ok {
		if err := validResponse.VisitGetProbeByIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateProbe operation middleware
func (sh *strictHandler) UpdateProbe(w http.ResponseWriter, r *http.Request, probeId ProbeIdPathParam) {
	var request UpdateProbeRequestObject

	request.ProbeId = probeId

	var body UpdateProbeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateProbe(ctx, request.(UpdateProbeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateProbe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateProbeResponseObject); ok {
		if err := validResponse.VisitUpdateProbeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xYXW/buBL9KwTvBXovIH/1pl8G+pA0d7sGik022WAfiiAYiyObrUQqJOXEG/i/L4aU",
	"bH15k3a9Qf0QwBZFnjlz5swwDzzWWa4VKmf59IHnYCBDh8Z/+wRzTC8xxdhp82uBZn1Oz+mRQBsbmTup",
	"FZ/yYxbrLIOBRdrAoWCptI7phH3F9fsVpAWylDazzGmWyNShYVoNecTxHrI8RT7lcVpYh+ZGivfi5btx",
	"MkEcvI5fHQ2O5uPJ4N0YXw/Em/HkzdHbZPz21STKjVyBw/fOFMgjLgnILYHkEVeQ0Zb+zBtbRsAjbuMl",
	"ZkABuHVOK6wzUi34ZhPxc6PnOBPn4JZ7wvxtiWx2SmG5JbKc1lM8Bp2RuMJmOE+JoYKdg1vuUPuNb6Tg",
	"ETd4W0iDgk8pyjr+fxtM+JT/a7RL4Cg8taMyksuweEPBlY/ozQ8GwaFfc4G3BVrnM290jsZJ9GtCsh47",
	"x+vDVsdE3DpwMr4pTPrYm5d+5ZVJtxjrsX6u73QdVbnS8y8YOzro/8Zocxa+drBnaC0ssE+lyyIDNTAI",
	"AuYpMqRtWLm+mb2ZWkEqRVAtqxTEEm0ycDzqkU8dfgVhL/YLtLlWFrvoPabH6KvH3z47bNB3ciNd0wcO",
	"QkiiBtLzBoRWbFGHRotVbQ9CbecgjWVuCY7FoNgcWWFRUG1oswAl/0AGSpQ0hsKxDb4fatX/9NopHYBP",
	"ufeATU/MzVLorehCydsCmRSonEwkOVPCoCzv/1xdzU7LtP/3uwq8lMyUF4Uv6Q67HuJOzE2AF5gbtJR8",
	"BsxKtUgr44m1SuSiMEArh56NehKJx29yiej5iz68XNinvFjYPVbhSa2B2G56vU8O9tgYWO8vwaDPHv+g",
	"14h3B1JJtWBaISMD0aZKSjjJa1s6zOyTcnC2hVfiBTqoE2gJqy+sNrO9Og8csauLT1SY8xKyaIp66Vxu",
	"p6MR5HJY/jooS3OYaD0UuLJLmbihNouGuD3zHW03MteLKi6MQeVYSFqjt3pkqsh88KgE7RlxiJ1cUcNP",
	"QKboKwpNJhU4en5dD2a7tIPrKhc9PbCJ7ieJqfADS+FXkwtUvtCtt+9UcieVv4MhbR24uTGphIw9RZ5f",
	"g1YXJkZ2B5Yp7ViiC9WSgmeH3Um3pKHnxX35GfT8qT4vdnv9rR5ZkrC/RO/CgsfobpLZRlBt0kVAK6VK",
	"dA/N5zOvgwwULIjNkxTir3N9z4K1UNjSef4ufj47uWSXa+WW6GRsyxXs+HzGI75CY8OW4+F4OKGodY4K",
	"csmn/H/DydA3OHBLH+8ooxkztqOdNy3Qy4NY8S1gRo3zk7RuC6Q+zH/uJ2q3ZLRv2N9cE2shEf7gl+Ox",
	"b9haOVQeA+R56tWl1eiLpaAevmVSbfmxZ78t7uo+AWm67XwotqPEJuJHB4TVnNF6AFXjoQnmwXY8Dr3M",
	"bJFlYNZ8yj+iY/DX8EkzsLB1j99EPNe2J8G14b28HqB1J1qsDxZ7z/Vg06wcGrY2HVFMDiuKs1opNrkP",
	"vhR7mILZIo7R2qRI03Wpg3fPp4Pjsu97lyRjtZBVnZamEQYpGfKa4b20Lgj11fMK1aFRQFcYs0ITukJb",
	"oyHlNGEqvAsR9WlyE7V9aPRQ3VU3wSpTdNgV7an/vRLtt9lS51be40dHXZ8OIgmAWiJhv2hWkl8K5uhg",
	"+Wg3rr3yrfXcZi4CV3Z7AcnAxUtqNLnRKylQsNlpv2H0NoSPGPrByXom/hHux89V9h9atrljphwYK3Z+",
	"wKSGJhBgz9dMOrs3izlF1c1jbWA9VBoP3zp6puontY7x87aOMM73to4fZYT40QQcMmufJmJ/rwk/tm35",
	"rBK1ZQZTnwWnWdlUduNQ/R+hlm+uN38GAAD//8I63lCoFgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
